# Generated by Django 3.0.7 on 2020-07-08 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0002_auto_20200708_1453'),
    ]

    operations = [
        migrations.RenameField(
            model_name='visitdetails',
            old_name='visitor_detail',
            new_name='visit_detail',
        ),
    ]
