# Generated by Django 3.0.7 on 2020-07-08 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0004_auto_20200708_1818'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventvisitor',
            name='tag',
        ),
        migrations.AddField(
            model_name='event',
            name='tag',
            field=models.ManyToManyField(to='basic.Tag'),
        ),
    ]
